services:
  app:
    restart: always
    image: lvckyzaros/github-commit-api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json
    networks:
      - github_api
